# Generated by Django 4.2.29 on 2026-03-30 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Mã dịch vụ tự sinh (DV0001, DV0002, ...)', max_length=20, null=True, unique=True, verbose_name='Mã dịch vụ')),
                ('name', models.CharField(help_text='Tên dịch vụ, tối đa 200 ký tự', max_length=200, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(help_text='URL thân thiện cho SEO', max_length=250, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('skincare', 'Chăm sóc da'), ('massage', 'Massage'), ('tattoo', 'Phun thêu'), ('hair', 'Triệt lông'), ('nails', 'Làm móng'), ('other', 'Khác')], db_index=True, default='skincare', max_length=20, verbose_name='Danh mục')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá (VNĐ)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Thời gian thực hiện dịch vụ (phút)', verbose_name='Thời lượng (phút)')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='service_slug_idx'), models.Index(fields=['is_active'], name='service_active_idx'), models.Index(fields=['code'], name='service_code_idx'), models.Index(fields=['-created_at'], name='service_created_idx'), models.Index(fields=['name'], name='service_name_idx'), models.Index(fields=['category', 'status'], name='service_category_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='service_duration_positive'),
        ),
    ]
