# Generated by Django 4.2.29 on 2026-03-20 13:12
# Initial migration for Spa ANA models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Service Model
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('category', models.CharField(
                    choices=[('skincare', 'Chăm sóc da'), ('massage', 'Massage'), ('tattoo', 'Phun thêu'),
                            ('hair', 'Triệt lông'), ('nails', 'Làm móng'), ('other', 'Khác')],
                    default='skincare', max_length=20, verbose_name='Danh mục')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá (VNĐ)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời lượng (phút)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['category', 'name'],
            },
        ),

        # CustomerProfile Model
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('full_name', models.CharField(default='', max_length=200, verbose_name='Họ và tên đầy đủ')),
                ('gender', models.CharField(
                    blank=True,
                    choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')],
                    max_length=1, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='customer_profile',
                    to='auth.user',
                    verbose_name='User')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),

        # Appointment Model
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.CharField(
                    default='TEMP001', editable=False, max_length=20, unique=True, verbose_name='Mã lịch hẹn')),
                ('appointment_date', models.DateField(verbose_name='Ngày hẹn')),
                ('appointment_time', models.TimeField(verbose_name='Giờ hẹn')),
                ('status', models.CharField(
                    choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'),
                            ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')],
                    default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú của khách hàng')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Ghi chú của nhân viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt lịch')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='spa.customerprofile',
                    verbose_name='Khách hàng')),
                ('service', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='spa.service',
                    verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),

        # ConsultationRequest Model
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, verbose_name='Email')),
                ('request_type', models.CharField(
                    choices=[('general', 'Tư vấn chung'), ('service', 'Tư vấn dịch vụ'),
                            ('promotion', 'Hỏi về khuyến mãi'), ('other', 'Khác')],
                    default='general', max_length=20, verbose_name='Loại yêu cầu')),
                ('content', models.TextField(default='', verbose_name='Nội dung cần tư vấn')),
                ('preferred_contact_time', models.CharField(
                    blank=True, max_length=200, verbose_name='Thời gian liên hệ mong muốn')),
                ('agree_contact', models.BooleanField(default=False, verbose_name='Đồng ý được liên hệ')),
                ('status', models.CharField(
                    choices=[('pending', 'Chờ xử lý'), ('contacted', 'Đã liên hệ'),
                            ('resolved', 'Đã giải quyết'), ('cancelled', 'Đã hủy')],
                    default='pending', max_length=20, verbose_name='Trạng thái')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Ghi chú xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': 'Yêu cầu tư vấn',
                'ordering': ['-created_at'],
            },
        ),

        # SupportRequest Model
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, verbose_name='Email')),
                ('support_type', models.CharField(
                    choices=[('feedback', 'Góp ý'), ('complaint', 'Khiếu nại'), ('inquiry', 'Hỏi đáp')],
                    max_length=20, verbose_name='Loại yêu cầu')),
                ('support_date', models.DateField(blank=True, null=True, verbose_name='Ngày xảy ra vấn đề')),
                ('appointment_code', models.CharField(blank=True, max_length=20, verbose_name='Mã lịch hẹn liên quan')),
                ('content', models.TextField(default='', verbose_name='Nội dung góp ý/khiếu nại')),
                ('expected_solution', models.TextField(blank=True, verbose_name='Giải pháp mong muốn')),
                ('agree_processing', models.BooleanField(default=False, verbose_name='Đồngý xử lý thông tin')),
                ('status', models.CharField(
                    choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'),
                            ('resolved', 'Đã giải quyết'), ('rejected', 'Đã từ chối')],
                    default='pending', max_length=20, verbose_name='Trạng thái')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Ghi chú xử lý')),
                ('resolution', models.TextField(blank=True, verbose_name='Phương án giải quyết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('related_service', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='spa.service',
                    verbose_name='Dịch vụ liên quan')),
            ],
            options={
                'verbose_name': 'Góp ý/Khiếu nại',
                'verbose_name_plural': 'Góp ý/Khiếu nại',
                'ordering': ['-created_at'],
            },
        ),
    ]
