# Generated by Django 4.2.29 on 2026-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_contact_time',
            field=models.CharField(blank=True, help_text='Ví dụ: Buổi sáng, Chiều, T2-T6...', max_length=200, verbose_name='Thời gian liên hệ mong muốn'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(help_text='Dùng cho login (username = phone)', max_length=20, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='agree_processing',
            field=models.BooleanField(default=False, verbose_name='Đồng意 xử lý thông tin'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='appointment_code',
            field=models.CharField(blank=True, help_text='Nếu vấn đề liên quan đến lịch hẹn cụ thể', max_length=20, verbose_name='Mã lịch hẹn liên quan'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='expected_solution',
            field=models.TextField(blank=True, help_text='Khách hàng muốn được giải quyết như thế nào', verbose_name='Giải pháp mong muốn'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='support_date',
            field=models.DateField(blank=True, help_text='Nếu có', null=True, verbose_name='Ngày xảy ra vấn đề'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_code'], name='spa_appoint_appoint_eaa417_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'appointment_date'], name='spa_appoint_custome_4ed048_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='spa_appoint_status_ae2caf_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status', 'created_at'], name='spa_consult_status_045b73_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['phone'], name='spa_custome_phone_eeef27_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='spa_service_slug_a6e634_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='spa_service_is_acti_b4d244_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['support_type', 'status'], name='spa_support_support_ba96ed_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['appointment_code'], name='spa_support_appoint_34a2fd_idx'),
        ),
    ]
