# Generated by Django 4.2.29 on 2026-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_alter_consultationrequest_preferred_contact_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Mã lịch hẹn'),
        ),
    ]
