# Generated by Django 4.2.29 on 2026-03-22 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spa', '0003_remove_appointment_code_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='agree_processing',
            field=models.BooleanField(default=False, verbose_name='Đồng ý xử lý thông tin'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='spa_service_code_6f4be5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='spa_service_created_82648c_idx'),
        ),
    ]
