# Generated by Django 4.2.29 on 2026-03-22 11:45

from django.db import migrations


def populate_service_codes(apps, schema_editor):
    """Generate codes for existing services"""
    Service = apps.get_model('spa', 'Service')

    # Get all services without codes, ordered by creation date
    services_without_codes = Service.objects.filter(code__isnull=True).order_by('created_at')

    prefix = 'DV'
    # Find the highest existing code number
    last_service = Service.objects.exclude(code__isnull=True).exclude(code='').order_by('-code').first()

    if last_service and last_service.code and last_service.code.startswith(prefix):
        try:
            last_number = int(last_service.code[len(prefix):])
            current_number = last_number + 1
        except (ValueError, IndexError):
            current_number = 1
    else:
        current_number = 1

    # Assign codes to services
    for service in services_without_codes:
        service.code = f"{prefix}{current_number:04d}"
        service.save(update_fields=['code'])
        current_number += 1


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_alter_service_options_service_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_service_codes, migrations.RunPython.noop),
    ]
