# Generated by Django 4.2.29 on 2026-03-23 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spa', '0006_add_complaint_models'),
    ]

    operations = [
        # Create Room model first
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã phòng')),
                ('name', models.CharField(max_length=50, verbose_name='Tên phòng')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Sức chứa (số khách cùng lúc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'ordering': ['code'],
            },
        ),
        # Add room field to Appointment BEFORE creating index on it
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.room', verbose_name='Phòng'),
        ),
        # Now add other fields
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng (phút)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Số khách'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('web', 'Khách đặt online'), ('admin', 'Lễ tân tạo')], default='web', max_length=10, verbose_name='Nguồn đặt lịch'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('not_arrived', 'Chưa đến'), ('arrived', 'Đã đến'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        # Add indexes AFTER room field exists
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['room', 'appointment_date'], name='spa_appoint_room_id_d415f6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['source', 'status'], name='spa_appoint_source_1ba913_idx'),
        ),
    ]