# Generated by Django 4.2.29 on 2026-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_room_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='related_service',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_code_idx',
            old_name='spa_appoint_appoint_eaa417_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_customer_date_idx',
            old_name='spa_appoint_custome_4ed048_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_status_date_idx',
            old_name='spa_appoint_status_ae2caf_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_room_date_idx',
            old_name='spa_appoint_room_id_d415f6_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_source_status_idx',
            old_name='spa_appoint_source_1ba913_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_slug_idx',
            old_name='spa_service_slug_a6e634_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_active_idx',
            old_name='spa_service_is_acti_b4d244_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_code_idx',
            old_name='spa_service_code_6f4be5_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_created_idx',
            old_name='spa_service_created_82648c_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(blank=True, editable=False, help_text='Mã tự sinh: APP + ngày + số thứ tự', max_length=20, unique=True, verbose_name='Mã lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_index=True, verbose_name='Ngày hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guests',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng khách tham gia dịch vụ', verbose_name='Số khách'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('not_arrived', 'Chưa đến'), ('arrived', 'Đã đến'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('skincare', 'Chăm sóc da'), ('massage', 'Massage'), ('tattoo', 'Phun thêu'), ('hair', 'Triệt lông'), ('nails', 'Làm móng'), ('other', 'Khác')], db_index=True, default='skincare', max_length=20, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, help_text='Mã dịch vụ tự sinh (DV0001, DV0002, ...)', max_length=20, null=True, unique=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Thời gian thực hiện dịch vụ (phút)', verbose_name='Thời lượng (phút)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Tên dịch vụ, tối đa 200 ký tự', max_length=200, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='URL thân thiện cho SEO', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='appt_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-created_at'], name='appt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='service_name_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'status'], name='service_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('guests__gte', 1)), name='appointment_guests_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='service_duration_positive'),
        ),
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
