# Generated by Django 4.2.29 on 2026-03-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_delete_consultationrequest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complaint',
            name='spa_complai_complai_2dbc34_idx',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
    ]
