# Generated by Django 4.2.29 on 2026-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_remove_complaint_type_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
