# Generated by Django 5.1.15 on 2026-04-12 04:29

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_code', models.CharField(blank=True, editable=False, max_length=24, unique=True, verbose_name='Mã phiên chat')),
                ('customer_type', models.CharField(choices=[('guest', 'Khách vãng lai'), ('authenticated', 'Khách đã đăng nhập')], db_index=True, default='guest', max_length=20, verbose_name='Loại khách hàng')),
                ('guest_session_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Khóa phiên khách vãng lai')),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng')], db_index=True, default='open', max_length=20, verbose_name='Trạng thái')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Trang bắt đầu chat')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='Xem trước tin nhắn cuối')),
                ('last_sender_type', models.CharField(blank=True, max_length=20, verbose_name='Loại người gửi cuối')),
                ('admin_unread_count', models.PositiveIntegerField(default=0, verbose_name='Số tin nhắn khách chưa đọc phía admin')),
                ('customer_unread_count', models.PositiveIntegerField(default=0, verbose_name='Số tin nhắn admin chưa đọc phía khách')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Thời gian tin nhắn cuối')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng phiên chat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='accounts.customerprofile', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Phiên chat',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Khách hàng'), ('admin', 'Nhân viên'), ('system', 'Hệ thống')], db_index=True, max_length=20, verbose_name='Loại người gửi')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Tên người gửi')),
                ('message_type', models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'Tệp tin')], default='text', max_length=20, verbose_name='Loại tin nhắn')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=chat.models.chat_attachment_upload_to, verbose_name='Tệp đính kèm')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('attachment_size', models.PositiveBigIntegerField(default=0, verbose_name='Kích thước file')),
                ('attachment_content_type', models.CharField(blank=True, max_length=120, verbose_name='Kiểu nội dung file')),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã tin nhắn phía client')),
                ('status', models.CharField(choices=[('sent', 'Đã gửi')], default='sent', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Phiên chat')),
            ],
            options={
                'verbose_name': 'Tin nhắn chat',
                'verbose_name_plural': 'Tin nhắn chat',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chat_code'], name='chat_session_code_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer', 'status'], name='chat_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer_type', 'status'], name='chat_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-last_message_at'], name='chat_last_message_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_message_session_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='chat_message_sender_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('session', 'client_message_id'), name='chat_message_client_unique'),
        ),
    ]
