# Generated by Django 3.1.14 on 2026-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('CSKH', 'CSKH'), ('Lễ tân', 'Lễ tân'), ('Nhân viên', 'Nhân viên')], default='Nhân viên', max_length=20, verbose_name='Vai trò'),
        ),
    ]
