# Generated by Django 4.2.29 on 2026-03-30 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('spa_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Mã khiếu nại')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề khiếu nại')),
                ('content', models.TextField(verbose_name='Nội dung khiếu nại')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Ngày xảy ra vấn đề')),
                ('appointment_code', models.CharField(blank=True, max_length=20, verbose_name='Mã lịch hẹn liên quan')),
                ('expected_solution', models.TextField(blank=True, verbose_name='Giải pháp mong muốn')),
                ('status', models.CharField(choices=[('new', 'Mới tạo'), ('pending', 'Chờ tiếp nhận'), ('assigned', 'Đã tiếp nhận'), ('processing', 'Đang xử lý'), ('waiting_customer', 'Chờ khách phản hồi'), ('resolved', 'Đã hoàn thành'), ('closed', 'Đã đóng')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('resolution', models.TextField(blank=True, verbose_name='Kết quả xử lý')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.customerprofile', verbose_name='Khách hàng')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa_services.service', verbose_name='Dịch vụ liên quan')),
            ],
            options={
                'verbose_name': 'Khiếu nại',
                'verbose_name_plural': 'Khiếu nại',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('customer', 'Khách hàng'), ('staff', 'Nhân viên CSKH'), ('manager', 'Quản lý')], default='staff', max_length=20, verbose_name='Vai trò người gửi')),
                ('sender_name', models.CharField(help_text='Lưu để hiển thị khi user bị xóa', max_length=200, verbose_name='Tên người gửi')),
                ('message', models.TextField(verbose_name='Nội dung phản hồi')),
                ('is_internal', models.BooleanField(default=False, help_text='Nếu true, khách hàng không thấy', verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='complaints.complaint', verbose_name='Khiếu nại')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Phản hồi khiếu nại',
                'verbose_name_plural': 'Phản hồi khiếu nại',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['complaint', 'created_at'], name='complaints__complai_153281_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tạo khiếu nại'), ('status_changed', 'Đổi trạng thái'), ('assigned', 'Phân công'), ('took_ownership', 'Nhận xử lý'), ('replied', 'Phản hồi'), ('resolved', 'Hoàn thành'), ('closed', 'Đóng'), ('reopened', 'Mở lại')], max_length=30, verbose_name='Hành động')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='Giá trị cũ')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='Giá trị mới')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint', verbose_name='Khiếu nại')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử khiếu nại',
                'verbose_name_plural': 'Lịch sử khiếu nại',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['complaint', '-performed_at'], name='complaints__complai_152686_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['code'], name='complaints__code_8a7e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='complaints__status_39c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to'], name='complaints__assigne_57ef98_idx'),
        ),
    ]
