# Generated by Django 4.2.29 on 2026-03-30 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('spa_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã phòng')),
                ('name', models.CharField(max_length=50, verbose_name='Tên phòng')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Sức chứa (số khách cùng lúc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.CharField(blank=True, editable=False, help_text='Mã tự sinh: APP + ngày + số thứ tự', max_length=20, unique=True, verbose_name='Mã lịch hẹn')),
                ('appointment_date', models.DateField(db_index=True, verbose_name='Ngày hẹn')),
                ('appointment_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng (phút)')),
                ('guests', models.PositiveIntegerField(default=1, help_text='Số lượng khách tham gia dịch vụ', verbose_name='Số khách')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('not_arrived', 'Chưa đến'), ('arrived', 'Đã đến'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('source', models.CharField(choices=[('web', 'Khách đặt online'), ('admin', 'Lễ tân tạo')], default='web', max_length=10, verbose_name='Nguồn đặt lịch')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú của khách hàng')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Ghi chú của nhân viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt lịch')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.customerprofile', verbose_name='Khách hàng')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.room', verbose_name='Phòng')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_services.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['appointment_code'], name='appt_code_idx'), models.Index(fields=['customer', 'appointment_date'], name='appt_customer_date_idx'), models.Index(fields=['status', 'appointment_date'], name='appt_status_date_idx'), models.Index(fields=['room', 'appointment_date'], name='appt_room_date_idx'), models.Index(fields=['source', 'status'], name='appt_source_status_idx'), models.Index(fields=['appointment_date', 'appointment_time'], name='appt_datetime_idx'), models.Index(fields=['-created_at'], name='appt_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('guests__gte', 1)), name='appointment_guests_at_least_one'),
        ),
    ]
